package sip

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"strings"
	"sync"

	"github.com/toprakgureli/santral-c/backend/configs"
	"github.com/toprakgureli/santral-c/backend/pkg/ami"
	"github.com/toprakgureli/santral-c/backend/pkg/crypt"
	"github.com/toprakgureli/santral-c/backend/pkg/errs"
	"github.com/toprakgureli/santral-c/backend/pkg/hash"
)

// IReloader applies PJSIP configuration changes on the switch.
type IReloader interface {
	Command(ctx context.Context, command string) (ami.Event, error)
}

// Credentials is a softphone's SIP registration data.
type Credentials struct {
	Extension    string `json:"extension"`
	Secret       string `json:"secret"`
	WebSocketURL string `json:"webSocketUrl"`
}

// Service provisions PJSIP endpoints and serves softphone credentials.
type Service struct {
	repo     *Repository
	cfg      configs.Asterisk
	reloader IReloader

	mu sync.Mutex // serializes file rewrites
}

// NewService builds a SIP service.
func NewService(repo *Repository, cfg configs.Asterisk, reloader IReloader) *Service {
	return &Service{repo: repo, cfg: cfg, reloader: reloader}
}

// Provision assigns a secret to a user's extension if needed, writes the PJSIP
// config and reloads. It is a no-op when the user has no extension.
func (s *Service) Provision(ctx context.Context, userID uint) error {
	u, err := s.repo.GetUser(ctx, userID)
	if err != nil {
		return errs.Internal(err)
	}
	if u == nil {
		return errs.NotFound("Kullanıcı bulunamadı.")
	}
	if u.SIPExtension == nil || *u.SIPExtension == "" {
		return errs.Invalid("Kullanıcının dahili numarası yok.", nil)
	}

	if u.SIPSecret == nil || *u.SIPSecret == "" {
		secret, genErr := hash.Token(18)
		if genErr != nil {
			return errs.Internal(genErr)
		}
		enc, encErr := crypt.Encrypt(s.cfg.SIPKey, secret)
		if encErr != nil {
			return errs.Internal(encErr)
		}
		if err := s.repo.SetProvisioning(ctx, userID, *u.SIPExtension, enc); err != nil {
			return errs.Internal(err)
		}
	} else if err := s.repo.SetProvisioning(ctx, userID, *u.SIPExtension, *u.SIPSecret); err != nil {
		return errs.Internal(err)
	}

	return s.Sync(ctx)
}

// Sync rewrites the provisioned-users config from the database and reloads
// PJSIP so the switch matches stored state.
func (s *Service) Sync(ctx context.Context) error {
	users, err := s.repo.Provisioned(ctx)
	if err != nil {
		return errs.Internal(err)
	}

	var b strings.Builder
	b.WriteString("; Generated by santral-c. Do not edit by hand.\n\n")
	for i := range users {
		ext := *users[i].SIPExtension
		secret, decErr := crypt.Decrypt(s.cfg.SIPKey, *users[i].SIPSecret)
		if decErr != nil {
			slog.Warn("sip secret could not be decrypted", "ext", ext, "error", decErr)
			continue
		}
		b.WriteString(endpointBlock(ext, secret, users[i].Name))
	}

	s.mu.Lock()
	err = os.WriteFile(s.cfg.UsersConfigPath, []byte(b.String()), 0o600)
	s.mu.Unlock()
	if err != nil {
		return errs.Internal(fmt.Errorf("pjsip users file could not be written: %w", err))
	}

	if s.reloader != nil {
		if _, err := s.reloader.Command(ctx, "pjsip reload"); err != nil {
			return errs.Internal(fmt.Errorf("pjsip reload failed: %w", err))
		}
	}
	return nil
}

// Credentials returns a user's own softphone registration data.
func (s *Service) Credentials(ctx context.Context, userID uint) (*Credentials, error) {
	u, err := s.repo.GetUser(ctx, userID)
	if err != nil {
		return nil, errs.Internal(err)
	}
	if u == nil {
		return nil, errs.NotFound("Kullanıcı bulunamadı.")
	}
	if u.SIPExtension == nil || u.SIPSecret == nil || *u.SIPSecret == "" {
		return nil, errs.NotFound("Hesabınız için softphone tanımlı değil.")
	}
	secret, err := crypt.Decrypt(s.cfg.SIPKey, *u.SIPSecret)
	if err != nil {
		return nil, errs.Internal(err)
	}
	return &Credentials{
		Extension:    *u.SIPExtension,
		Secret:       secret,
		WebSocketURL: s.cfg.WebSocketURL,
	}, nil
}

func endpointBlock(ext, secret, name string) string {
	callerID := fmt.Sprintf("%s <%s>", sanitize(name), ext)
	var b strings.Builder
	fmt.Fprintf(&b, "[%s](endpoint-webrtc)\n", ext)
	fmt.Fprintf(&b, "auth = %s\n", ext)
	fmt.Fprintf(&b, "aors = %s\n", ext)
	fmt.Fprintf(&b, "callerid = %s\n", callerID)
	fmt.Fprintf(&b, "[%s](auth-userpass)\n", ext)
	fmt.Fprintf(&b, "username = %s\n", ext)
	fmt.Fprintf(&b, "password = %s\n", secret)
	fmt.Fprintf(&b, "[%s](aor-single)\n\n", ext)
	return b.String()
}

// sanitize strips characters that would break a pjsip.conf callerid line.
func sanitize(name string) string {
	replacer := strings.NewReplacer("\n", " ", "\r", " ", "<", "", ">", "", ";", "", "[", "", "]", "")
	trimmed := strings.TrimSpace(replacer.Replace(name))
	if trimmed == "" {
		return "Agent"
	}
	return trimmed
}
